LiveFastEatTrashRaccoon/RaccoonForLemmy

README.md

This PR rolls back the breaking changes from removing references to the original repository and adds a new disclaimer.

fix: rolled back README breaking changes, added new disclaimer

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/CollapsedCommentCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/CommentCard.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt

This PR makes use of an uniform logic between expanded and collapsed comments as far and bar width and text indentation are concerned.

enhancement: uniform comment cards

---

README.md

This PR restores the correct versions for the badge in README.md.

chore: update badges in README.md

---

README.md

The project is now using Kotlin 2.0.21 so it's better to keep the badge up to date! 👀

chore: update Kotlin version in README badge

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/CommentCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/InboxCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/texttoolbar/CustomTextActionModeCallback.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/texttoolbar/CustomTextToolbar.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/texttoolbar/GetCustomTextToolbar.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/texttoolbar/GetCustomTextToolbar.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/texttoolbar/GetCustomTextToolbar.kt
unit/rawcontent/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/rawcontent/RawContentDialog.kt

This allows closing the toolbar when no selection has been made by the user.

enhancement: add 'cancel' option to text toolbar

---

README.md
docs/index.md
domain/inbox/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/inbox/notification/CheckNotificationWorker.kt

This PR updates the contact information in the project README and webpage, adding the new Matrix room to the options.

chore: udpate documentation with new contacts

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/CustomModalBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SortBottomSheet.kt
core/notifications/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsScreen.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt
unit/instanceinfo/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/instanceinfo/InstanceInfoScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

This PR rewrites SortBottomSheets discarding Voyager's bottom sheets and replacing it with the Material3 component.

refactor: rewrite sort bottom sheet as Material3 modal bottom sheet

---

feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontScreen.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ConfigureContentViewScreen.kt

Render preview of the font size and typeface in the selection bottom sheets.

fix: use font face and size in selection bottom sheets

---

core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/data/FontScale.kt
core/commonui/components/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/components/PlaceholderImage.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsHeader.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsImageInfo.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsRow.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsSwitchRow.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsTextualInfo.kt
feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/menu/ProfileMenuContent.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsScreen.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ConfigureContentViewScreen.kt
unit/drawer/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/drawer/ModalDrawerContent.kt
unit/editcommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/editcommunity/EditCommunityScreen.kt

This PR reviews the UI components used for settings (and the image placeholder for avatars) and updates the lists where these components were used.

chore: review inter-item spacings in setting lists and side menus

---

README.md
core/commonui/components/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/components/VideoPlayer.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardVideo.kt
core/resources/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/resources/CoreResources.kt
docs/tech_manual/tech_stack.md
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedResources.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/medialist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/medialist/MediaListScreen.kt
unit/medialist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/medialist/components/MediaItem.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageScreen.kt

This PR makes it possible to open videos in the "attachment detail" screen (the same one used for images) unmuted by clicking on the FullScreen button in the video card.

feat: make it possible to open videos full screen

---

docs/user_manual/main.md

chore: add table of contents and internal links in user manual

---

core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/data/FontScale.kt

As per title.
Original request [on Lemmy](https://feddit.org/comment/3105880).

enhancement: review font scale factors

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/pull_request_template.md
PRIVACY.md

chore: add pull request template and review issue templates

---

androidApp/build.gradle.kts
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/CustomModalBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SelectNumberBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SliderBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SortBottomSheet.kt
core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/Utils.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/manageaccounts/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageaccounts/ManageAccountsBottomSheet.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/SelectInstanceBottomSheet.kt

This PR fixes the rendering of lists inside quotes, refining the work done in #62.
Refine code coverage.
--- 
Original report [on Lemmy](https://sh.itjust.works/post/28364457).

fix: Markdown rendering of list in quotes

---

androidApp/build.gradle.kts
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepositoryTest.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/usecase/DefaultExportSettingsUseCaseTest.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/usecase/DefaultImportSettingsUseCaseTest.kt

This PR adds some missing tests to `:core:persistence` which were lowering the coverage reports.

chore: add missing tests to :core:persistence

---

unit/acknowledgements/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/acknowledgements/components/AcknowledgementItem.kt
unit/acknowledgements/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/acknowledgements/components/AcknowledgementItemPlaceholder.kt
unit/acknowledgements/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/acknowledgements/datasource/DefaultAcknowledgementsRemoteDataSource.kt
unit/acknowledgements/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/acknowledgements/main/AcknowledgementsScreen.kt

This PR fixes a couple of typos in the Acknowledgements screen and corrects the URL of the file used internally to get the list of contributors.

fix: improve acknowledgements screen

---

domain/lemmy/pagination/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/DefaultExplorePaginationManagerTest.kt
domain/lemmy/pagination/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/DefaultExplorePaginationManager.kt

This PR leverages what has been done in #152 to improve the search function as requested in #159.
Given the fact that URLs can now be resolved by the back-end, this change is almost for free 🎉

enhancement: allow searching post/comments/users/communities by URLs

---

core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultAccountRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/AccountRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultAccountRepository.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCase.kt
feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/notlogged/ProfileNotLoggedScreen.kt
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/main/MainScreen.kt
unit/drawer/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/drawer/content/ModalDrawerContent.kt
unit/login/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/login/LoginScreen.kt
unit/login/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/login/LoginViewModel.kt
unit/manageaccounts/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageaccounts/ManageAccountsViewModel.kt

This PR fixes the account switch behaviour, which was not properly intercepted and displayed in the UI.
I remember to have already solved something like this back in the old ages… but it's no longer there.

fix: make sure account changes are observed

---

core/appearance/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/repository/DefaultThemeRepositoryTest.kt

This PR adds some missing test for `DefaultThemeRepository`.

chore: add tests for theme repository

---

core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Extensions.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Locales.kt

This PR sort languages by locale code alphabetically. This is in preparation for new languages to come.

chore: sort locales alphabetically

---

docs/acknowledgements.json
docs/index.md

This PR mentions the new translators in the acknowledgements.

chore: update acknowledgements

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/EditUserTagDialog.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/di/PostDetailModule.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailViewModel.kt
unit/usertags/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/usertags/list/UserTagsMviModel.kt
unit/usertags/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/usertags/list/UserTagsScreen.kt
unit/usertags/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/usertags/list/UserTagsViewModel.kt

This PR continues the work of #223 with special tags, in follow up to [this comment](https://github.com/LiveFastEatTrashRaccoon/RaccoonForLemmy/issues/222#issuecomment-2573754789) on #222.

enhancement: user tags and roles management • iteration 2

---

core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt

This PR fixes a bug introduced in #249 in the day count for date formatting.

fix: day count in date formatting

---

core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultLongToLongMapSerializerTest.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultPostLastSeenDateRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/di/PersistenceModule.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultLongToLongMapSerializer.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultPostLastSeenDateRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSortSerializer.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/LongToLongMapSerializer.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/PostLastSeenDateRepository.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCaseTest.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLogoutUseCaseTest.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultSwitchAccountUseCaseTest.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/di/IdentityModule.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCase.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLogoutUseCase.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultSwitchAccountUseCase.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailMviModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/di/PostDetailModule.kt

This PR adds the possibility to see unread new comments (since the last time that post was opened) with a different background color.

feat: show unread comments with different background in post detail

---

unit/manageban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageban/ManageBanScreen.kt
unit/manageban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageban/ManageBanViewModel.kt

This PR improves the "Bans and filters" screen:
- FAB menu item visibility;
- refresh was not working as expected;
- access shared data in mutual exclusion;

refactor: improve bans and filters screen

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/Extensions.kt
domain/lemmy/data/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/data/PostModel.kt

This PR makes it possible to display URLs pointing to public images on Imgur as pictures rather than links.
Partially related to #254.

enhancement: display public images on Imgur

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/Options.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailMviModel.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityMviModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListMviModel.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListViewModel.kt

This PR implements the possibility to manually mark a post as read/unread from its drop-down menu.

feat: manually mark items as read or unread

---

core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Extensions.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Locales.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
docs/_config.yml
docs/acknowledgements.json
docs/index.md
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt

This PR  add the support for Tamil language and updates the acknowledgements.
The theme of the website was changed to a more readable one (Cayman).

chore: add support for ta l10n

---

core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Extensions.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Locales.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
docs/acknowledgements.json
docs/index.md
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt

This PR adds the support for the Latvian localization, thanks to the translation by @Coool.

chore: add support for lv l10n

---

core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/imageload/ImageUtils.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/imageload/DefaultImageLoaderProvider.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/imageload/ImageUtils.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/imageload/ImageUtils.kt

This PR fixes an issue due to which images were not loaded by Coil on iOS (see thread in #408).

fix: network image loading on iOS

---

core/commonui/components/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/components/SwipeActionCard.kt

This PR is another workaround for [this](https://issuetracker.google.com/issues/252334353) old issue (reported almost 3 years ago and never addressed).

fix: increase swipe positional threshold in dismissable cards
