LiveFastEatTrashRaccoon/RaccoonForLemmy

README.md

This PR restores the assets which were included in the old `README.md`. Moreover, it updates some of the textual information contained in this file too, e.g. the references to Moko resources which is not used any more.
The current `README.md` was taken from a snapshot of an older version, so the features section was not entirely up-to-date: I've tried to keep the same synthetic style but mention all the features that have been added since the time the snapshot was taken.

chore: restore README.md

---

docs/_config.yml
unit/about/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/about/AboutConstants.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ContentPreview.kt

Corrected example URLs from the project renaming.  
NOTE:  A few still remain: 
- `docs/config.yml`:  **26** -  _original github.io website_
- `feature/settings/[...]/feature/settings/main/SettingsScreen.kt`:  **428**  - _user manual on github.io_
- `unit/about/[...]/unit/about/AboutConstants.kt`:  **10**  - _Google Play url_

chore: update example urls

---

core/api/build.gradle.kts
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/provider/DefaultServiceProvider.kt
gradle/libs.versions.toml

This PR updates a series of dependencies to the latest versions:
- androidx-media3 from 1.4.0 to 1.4.1
- androidx-work from 2.9.0 to 2.9.1
- AGP from 8.5.1 to 8.5.2
- Kotlin from 2.0.0 to 2.0.20
- KSP from 2.0.0-1.0.23 to 2.0.20-1.0.24
- Ktorfit from 2.0.0-rc01 to 2.0.1
The latter one required some adaptation since Ktorfit 2.0.1 is not backwards compatible with the previous RC, especially in that they deprecated the old generic `<T> fun create(): T` factory method to create service instances and rely on a series of autogenerated extension functions, each of which specific for a single service.

chore: update deps

---

unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostScreen.kt

This PR contains a fix for #6 which avoid the overlapping between the `TextFormattingBar` and the bottom edge of the `TextField`. 
The solution was simpler than expected: just like in the inbox chat screen, `TextFormattingBar` belongs to the `bottomBar` parameter of the `Scaffold` and the `imePadding()` Modifier should be applied to the Scaffold itself instead of on its content.

fix: text formatting bar in post and reply creation

---

core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt

`SimpleDateFormat` is not thread safe and is frowned upon by and Java developer nowadays. When I used I was thinking «I'll replace it when I have time, now I just need to put together something working" and then I forgot about it.
Additionally, this PR introduces a consistent use of `ZonedDateTime` whenever possible.

refactor: replace `SimpleDateFormat` with `DateTimeFormatter`

---

androidApp/src/main/AndroidManifest.xml
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/gallery/GalleryHelper.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatScreen.kt
unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
unit/editcommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/editcommunity/EditCommunityScreen.kt

As stated [here](https://developer.android.com/training/data-storage/shared/photopicker#device-availability) the photo picker is not available on Android < 11 (API level 30) and this case, if not handled, leads the app to crash.
This PR introduces the fallback on the GMS backported version of the picker, moreover it adds a check to avoid processing empty byte arrays (e.g. when the user dismisses the picker bottom sheet).
The `PickVisualMediaRequest` is now created with its Builder instead of relying on the constructor, this is just a syntactic change with no impact on functionality or behaviour.

fix: pick image from gallery on Android < 11

---

core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/gallery/GalleryHelper.kt

The flag `FLAG_GRANT_READ_URI_PERMISSION` is only needed when the access to the file needs to be preserved for a long time (across app restarts or when the app is sent to background) to perform long-running or periodic operations.
This is not the case with RFL, because the access to the file is only needed for uploading it to the server in a fire-and-forget way. The persistable permission request could cause crashes on some devices because manufacturer may impose a stricter limit to the amount of persistable permissions an app can be granted, and there is anyway a limit by Google to 512 (before 2020 it was 128).

fix: remove persistable URI permission `FLAG_GRANT_READ_URI_PERMISSION`

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/CustomModalBottomSheet.kt

Avoid dismissing bottom sheets on long press if there is no callback, because this would result in an incorrect state.

fix: avoid dismissing bottom sheets on long press

---

docs/index.md

This restores the "further reading" section in the project homepage.

chore: update links in project homepage

---

domain/inbox/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/inbox/notification/CheckNotificationWorker.kt
domain/inbox/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/inbox/notification/DefaultInboxNotificationChecker.kt

This modernizes the `CheckNotificationWorker` migrating it to be a `CoroutineWorker` (and thus avoiding having to deal with its internal scope). Moreover, the `CoroutineDispatcher` should NOT be passed as a constructor parameter because this prevents proper instantiation by the system factory.
Additionally, this PR changes `DefaultInboxNotificationChecker` to perform a one-shot execution at the beginning, scheduling repeated tasks at a later moment, to avoid an initial delay that the system may happen to insert.

refactor: background notification checks

---

core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/Utils.kt

There was an issue with markdown due to which, if inside a quote there was an empty line, all the text coming afterwards was not rendered, e.g.:
```
> some random quote
> 
> this is not rendered
```
Original report [on Lemmy](https://lemmy.world/post/21437975).
This PR add as sanitization workaround to avoid that issue. I am more and more disappointed with the Markdown rendering library, and I really wished something else existed for Compose Multiplatform.

fix: make sure text after an empty quote is rendered

---

docs/_config.yml
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsConstants.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsScreen.kt

This PR restores the in-app link to user manual.

fix: restore user manual URL

---

unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

This PR fixes a bug due to which the UI was unresponsive after dismissing the block bottom sheet in the home screen. Double checked that that bottom sheet is used just there.

fix: reset UI state when block option selected

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SelectNumberBottomSheet.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ConfigureContentViewScreen.kt

Continue bottom sheet overhaul rewriting `SelectNumberBottomSheet` using Material3's `ModalBottomSheet`.

refactor: migrate SelectNumberBottomSheet to M3 modal bottom sheet

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SliderBottomSheet.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ConfigureContentViewScreen.kt

This PR migrated `SliderBottomSheet` to Material3's `ModalBottomSheet`.

refactor: migrate SliderBottomSheet to M3

---

feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
unit/drawer/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/drawer/ModalDrawerContent.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/SelectInstanceBottomSheet.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/components/SelectInstanceItem.kt

We're finally getting there! `SelectInstanceBottomSheet` is the second-to-last bottom sheet still using Voyager's `BottomSheetNavigator`.
This migration was a little more complex because the bottom sheet had an associated view model, so it need to get tied to the lifecycle of the container screen.

refactor: migrate SelectInstanceBottomSheet to M3

---

unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt

As per title, this fixes a bug due to which after changing the default sort type for a community the UI became unresponsive.

fix: restore UI state after closing default sort bottom sheet in community detail

---

core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultInstanceSelectionRepository.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/components/SelectInstanceItem.kt

This PR updates the default instance list in the "Select instance" bottom sheet:
- remove feddit.de ⚰️ ;
- add feddit.it, infosec.pub, lemmy.sdf.org, mander.xyz;
- sort items alphabetically;
- reset list if contains legacy values.

enhancement: add new instances to default list

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardBody.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardTitle.kt

This PR fixes the text style used for links in post body and titles.

fix: text style used for links in Markdown

---

unit/drawer/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/drawer/components/DrawerHeader.kt

The dropdown button in the navigation drawer's header had the wrong bounds for the ripple effect. This PR makes it look like a real M3 button.

fix: drawer header dropdown button ripple

---

README.md
feature/inbox/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/inbox/main/InboxScreen.kt
gradle/libs.versions.toml
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/components/ExploreTopBar.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/components/PostsTopBar.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListScreen.kt

This PR updates Compose Multiplatform to 1.7.1 and fixes the ripple effects in some application top bars.

chore(deps): update compose multiplatform from 1.7.0 to 1.7.1

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardImage.kt

This PR adds a "visibility on"/"visibility off" on sensitive images so that they can revealed directly in the timeline without having to open the post detail.
The mechanism is similar to the one of Raccoon for Friendica (where it proved to be the way to go!).

feat: add button to reveal images in timelines

---

.github/pull_request_template.md
PRIVACY.md
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardVideo.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageScreen.kt

This PR fixes some issues with video rendering:
- in the timeline the view was unbound, which lead to two unwanted behaviours:
- the video could extend to occupy a large portion of the timeline while scrolling
- some video controls like the seek bar were incorrectly positioned, e.g. on the top instead of at the bottom
- in the attachment screen when opening the video, the view was cropped if the video had an aspect ratio > 1.
Nothing to declare.

fix: video rendering timeline and attachment detail

---

core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/data/FontScale.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt

This PR changes the default name of the JSON where settings are going to be exported to. The reason is to make Raccoon for Lemmy settings easily distinguishable from Raccoon for Friendica settings.
Font scale factors were updated because they still "felt wrong". Now the normal factor has the same value of Raccoon for Friendica.

fix: change settings export default file name; update font scale factors

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/CustomModalBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SelectNumberBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SliderBottomSheet.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/SortBottomSheet.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/manageaccounts/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageaccounts/ManageAccountsBottomSheet.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/SelectInstanceBottomSheet.kt

This PR restores a xs bottom padding in modal bottom sheets and inserts an s padding in filtered contents (bookmarks, votes and moderated contents).

fix: add missing insets in modals and below section selectors

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/CommunityAndCreatorInfo.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardImage.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardPlaceholder.kt
unit/medialist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/medialist/components/MediaItem.kt

This PR fixes the image height in post cards, especially in compact mode. In particular:
- in compact mode images are constrained vertically and the `fullHeightImages` option has no effect;
- also, in compact mode, user and community are on one line to save vertical space;
- in card and full mode, images are set with a maximum height and scaled to fill the space, unless you enable `fullHeightImages` .

fix: image height in post cards

---

core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/EditFormattedlInfoDialog.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/EditTextualInfoDialog.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/NumberPickerDialog.kt
unit/ban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/ban/BanUserScreen.kt
unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatScreen.kt
unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
unit/login/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/login/LoginBottomSheet.kt
unit/moderatewithreason/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/moderatewithreason/ModerateWithReasonScreen.kt
unit/selectinstance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/selectinstance/dialog/ChangeInstanceDialog.kt

This PR replaces calls to `KeyboardOptions` constructor with `autoCorrect` parameter in favour of the `autoCorrectEnabled` overload.
This should have been done after updating Compose Multiplatform to 1.7.1.

fix: remove deprecated constructor for KeyboardOptions

---

unit/ban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/ban/BanUserScreen.kt
unit/ban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/ban/BanUserViewModel.kt
unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentViewModel.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostViewModel.kt
unit/modlog/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/modlog/ModlogScreen.kt
unit/modlog/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/modlog/ModlogViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListViewModel.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailViewModel.kt

This PR solves a bug introduces after migrating the whole project to Koin with annotations. Apparently, nullable types are not supported so if an `@InjectedParam` had a null value at runtime, its actual value is "not defined" (can be the first non-null values of the other params or result in an error).
Curiously enough, when using the DSL everything worked perfectly, so it's definitely something related to Koin Annotations 2.0.0-Beta2.
The solution to this was always pass non-null values, marking the case when a value is missing with a sentinel (e.g. `0L` for IDs, etc.).

fix: avoid using nullable types as @InjectedParams

---

build-logic/convention/src/main/kotlin/extensions/ConfigureAndroidTest.kt
build-logic/convention/src/main/kotlin/plugins/AndroidTestPlugin.kt
core/architecture/testutils/build.gradle.kts
core/persistence/build.gradle.kts

This PR continues the work of #143 and #144 and applies the convention plugins to `:core:persistence` and `:core:architecture:testutils`.
Moreover it refactors `AndroidTestPlugin` to have the same structure of the other plugins and be more maintainable.
I didn't manage to do it yesterday but I was in a hurry, today I said to myself "I'll have a more thorough look at it with more time" and it worked. Probably sqldelight plugin is picky on the order in which it is applied with respect to the other ones.

chore(build): apply convention plugins to :core:persistence

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt

This PR fixes the image detail opening behaviour: if the URL of the post is an image, it is the high-resolution image URL which should be opened instead of the thumbnail one.

fix: open image detail with high res URL instead of thumbnail

---

unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageScreen.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageViewModel.kt

This PR fixes a couple of bugs in `ZoomableImageScreen`:
- the loading state was not properly rendered in the UI;
- the top app bar action buttons did not have the correct Material design padding and the ripple effect was square.

fix: image detail loading state and top bar actions

---

CONTRIBUTING.md
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Extensions.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
shared/src/commonMain/composeResources/values-de/strings.xml
shared/src/commonMain/composeResources/values-es/strings.xml
shared/src/commonMain/composeResources/values-fi/strings.xml
shared/src/commonMain/composeResources/values-fr/strings.xml
shared/src/commonMain/composeResources/values-ga/strings.xml
shared/src/commonMain/composeResources/values-it/strings.xml
shared/src/commonMain/composeResources/values-pl/strings.xml
shared/src/commonMain/composeResources/values-pt-rBR/strings.xml
shared/src/commonMain/composeResources/values-pt/strings.xml
shared/src/commonMain/composeResources/values-ua/strings.xml
shared/src/commonMain/composeResources/values-zh-rCN/strings.xml
shared/src/commonMain/composeResources/values-zh-rHK/strings.xml
shared/src/commonMain/composeResources/values-zh-rTW/strings.xml
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt

This PR moves language names to resources as untranslatable messages. Moreover the `lang` string was useless and could be removed.

refactor(l10n): move language names to resources

---

unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorScreen.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageScreen.kt

This PR fixes a bug due to which instantiating viewmodels with injected args failed due to the wrong overload of `rememberScreenModel` being used.
This bug was introduced in #181 due to having to migrate everything manually.

fix: injected params in view models

---

shared/src/commonMain/composeResources/values-es/strings.xml
shared/src/commonMain/composeResources/values-ga/strings.xml
shared/src/commonMain/composeResources/values-pl/strings.xml
shared/src/commonMain/composeResources/values-ua/strings.xml
shared/src/commonMain/composeResources/values/strings.xml

This PR removes escaped apostrophes which in Compose resources are treated literally.
This may break in future imports from Weblate so I'll have to be careful.

fix: remove escapes for apostrophes

---

core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/di/PersistenceModule.kt

This PR fixes a crash due to which it was not possible to instantiate settings import and export use cases, which led to a crash when opening the Advanced settings screen.
This was accidentally introduced in #181.

fix(di): add missing bindings for settings import and export use cases

---

core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepositoryTest.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultUserTagRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/data/UserTagMemberModel.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/di/PersistenceModule.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultUserTagRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/UserTagRepository.kt
core/persistence/src/commonMain/sqldelight/com/livefast/eattrash/raccoonforlemmy/core/persistence/usertagmembers.sq
core/persistence/src/commonMain/sqldelight/com/livefast/eattrash/raccoonforlemmy/core/persistence/usertags.sq
core/persistence/src/commonMain/sqldelight/migrations/39.sqm

This PR contains the persistence and domain layers needed to implement user tagging as tracked by #195.
Future PRs will contain the UI and the business logic needed to manage tags and membership.

feat: implement user tags • part 1

---

domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/di/IdentityModule.kt

This PR fixes a misconfiguration in the binding for `ServiceProvider` to instantiate `DefaultSwitchAccountUseCase`, which led to an application crash when trying to switch accounts.
Again this was introduced by #181 which was done in a hurry to unblock the F-Droid release (which is still stuck BTW so there was no need to rush).

fix(di): fix misconfigured binding for ServiceProvider

---

unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt

This PR fixes the title of the bottom sheet to select the search result type in the Explore section.

fix: explore result type bottom sheet title

---

unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt

This PR fixes the title of the bottom sheet used to select the listing type in the Explore section.
<details><summary>Related PRs</summary>
- #205 
</details>
Both were introduced in the bottom sheet migration done in #44, #45

fix: explore listing type bottom sheet title

---

core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/data/SettingsModel.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/usecase/SerializableSettings.kt
core/persistence/src/commonMain/sqldelight/com/livefast/eattrash/raccoonforlemmy/core/persistence/settings.sq
core/persistence/src/commonMain/sqldelight/migrations/40.sqm
domain/lemmy/pagination/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/DefaultExplorePaginationManagerTest.kt
domain/lemmy/pagination/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/DefaultExplorePaginationManager.kt
domain/lemmy/pagination/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/ExplorePaginationSpecification.kt
domain/lemmy/pagination/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/pagination/di/LemmyPaginationModule.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsMviModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreViewModel.kt

This PR makes it possible to restrict the local user search (i.e. when in the Explore section the result type is `Users` and the listing type is `Local`) to results which are on the current instance (or the guest one if you are browsing a foreign instance).
<div align="center">
</div>

feat: restrict local user search to results on the current instance

---

core/appearance/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultColorSchemeProvider.kt
core/appearance/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/repository/DefaultThemeRepositoryTest.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/repository/DefaultThemeRepository.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/repository/ThemeRepository.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/AppTheme.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/ColorSchemeProvider.kt
core/appearance/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultColorSchemeProvider.kt
core/notifications/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/data/SettingsModel.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepository.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/usecase/SerializableSettings.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontViewModel.kt
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/App.kt

This PR  fixes a bug due to which the "System" theme was interpreted as light. Thanks to the beta testers who reported it [on Reddit](https://www.reddit.com/r/AndroidClosedTesting/comments/1hrddhp/comment/m51jw08)!
This bug was probably introduced by #12 when the `UiTheme.Default` value was added instead of `null` which was previously interpreted as default.

fix: default theme color

---

domain/lemmy/repository/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultGetSiteSupportsMediaListUseCaseTest.kt
domain/lemmy/repository/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultMediaRepositoryTest.kt

This PR adds more test cases (e.g. for `:domain:lemmy:repository`) to prevents builds from being marked as failed due to coverage threshold.

chore: improve unit test coverage

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsSwitchRow.kt

This PR makes `SettingsSwitchRow` more accessible by using the `toggleable` Modifier with its built-in semantics.
This is directly taken from Raccoon for Friendica 🦝

fix: make settings switch row more accessible

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/SettingsSwitchRow.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/CustomColorPickerDialog.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/EditTextualInfoDialog.kt
core/commonui/modals/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/modals/EditUserTagDialog.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontScreen.kt
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt

This PR allows to manually insert a color as hex code for user tag colors (with validation).
Other related small fixes:
- vertical padding in `SettingsSwitchRow`;
- make theme color selection bottom sheet skip partially expanded state.

enhancement: allow manual hex code selection in color picker for user tags

---

core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/Utils.kt

This PR fixes a bug due to which, under some circumstances, blank lines were "swallowed" during input sanitization before Markdown parsing. However, since this wasn't enough, blank lines are artificially inserted to better separate paragraphs.
There were some deprecated function usages from Mike's markdown renderer, this PR migrates their usage to the new APIs.

fix: better paragraph separation

---

unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatScreen.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/messages/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/messages/InboxMessagesScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

This PR adds the post `read` property to the compound key used to determine if an item needs recomposition in a lazy list. Its being not included could lead to posts not marked as read immediately when first entering the detail.
Apparently it was like this in the beginning (because I vaguely remember so, and because in inbox the `read` property was already included). Maybe some excessive optimization in the past brought its removal and, therefore, the bug.

fix: include post read property in item keys

---

unit/communityinfo/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communityinfo/CommunityInfoScreen.kt
unit/userinfo/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userinfo/UserInfoScreen.kt

This PR fixes a bug due to which community info and user info did not update when they are opened again.

fix: set custom screen keys for side info panels

---

core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateUtils.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/datetime/DateFunctions.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
shared/src/commonMain/composeResources/values/strings.xml

This PR allows to see dates and durations with a higher detail of precision. Moreover it makes the "month" abbreviation clearer and, wherever possible, relies on Kotlin duration functions rather than manual calculations.

enhancement: date, time and period formatting

---

core/api/build.gradle.kts
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/dto/DeleteAccountForm.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/service/UserService.kt
core/commonui/components/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/components/ProgressHud.kt
core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
domain/lemmy/repository/build.gradle.kts
domain/lemmy/repository/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultUserRepositoryTest.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultUserRepository.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/UserRepository.kt
gradle/libs.versions.toml
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsMviModel.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsViewModel.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/components/DeleteAccountDialog.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/di/AccountSettingsModule.kt

This PR adds the possibility to delete one's own account from the "Web preferences" screen.
The POST `user/delete_account` works differently from the documentation,[^1] so some adaptations, including installing a dedicated converter for network responses, were needed.
[^1]: Because it's Lemmy, folks, of course the software behaves differently from the specs!

feat: add possibility to delete account from web preferences

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardBody.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCardTitle.kt
core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/Utils.kt

This PR fixes a couple of bugs for markdown quotes:
- lists are sometimes skipped (plus, bullets were removed from an old fix)
- the Italic style was applies (because so it was in the original default typography) which can be confusing for users.
This solves both issues reported in #257.

fix(md): formatting quotes and bulleted lists inside quotes

---

unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatScreen.kt
unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatViewModel.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailMviModel.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsMviModel.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsViewModel.kt
unit/mentions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/mentions/InboxMentionsMviModel.kt
unit/mentions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/mentions/InboxMentionsScreen.kt
unit/mentions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/mentions/InboxMentionsViewModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityMviModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedMviModel.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedViewModel.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListMviModel.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListViewModel.kt
unit/replies/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/replies/InboxRepliesMviModel.kt
unit/replies/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/replies/InboxRepliesScreen.kt
unit/replies/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/replies/InboxRepliesViewModel.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailMviModel.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailViewModel.kt

This PR deals with opening post detail differently to avoid a concurrency issue (due to the post being marked as read before the view model could update its state due to entering the paused state).
This is a tentative fix for #239.

fix: avoid concurrency issue while posts are being marked as read before opening detail

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
domain/lemmy/data/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/data/PostModel.kt

This PR  iterates over #154 because a similar bug was reintroduced and the app failed opening the same post reported in #142.
This was tested both for Compact and Card layouts.

fix: simplify video and image post URL matching

---

domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/urlhandler/DefaultPostProcessor.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/urlhandler/DefaultUserProcessor.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsViewModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
unit/myaccount/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/myaccount/ProfileLoggedViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/utils/CommentUtils.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListViewModel.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailViewModel.kt

This PR removes argument names for method invocations with a single param where there is no disambiguation needed. Additionally, it contains some other minor stylistic improvements, removing redundant newlines and the like.
I realized this was creating confusion to newcomers, thinking the presence or absence of an argument name made a difference where it didn't.

chore: remove arg name for single param invocations

---

unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreViewModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

This PR fixes the sort bottom sheet when used to select a value suitable for comments (i.e. with no "top" subselection).

fix: disallow "top" sort type expansion for comments in post detail, user detail, explore

---

core/appearance/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/BarColorProvider.kt
core/appearance/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsMviModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/di/SettingsTabModule.kt

This PR removes the UI bar theme option from the advanced settings screen because it has no effect on Android >= 15 (and this is intended).

fix: add bar theme option only if supported

---

core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/Utils.kt

This PR solves a bug introduced in an attempt to work around an issue in the Multiplatform Markdown Renderer library due to which multi-paragraph quotes were cut off after the first paragraph.
Given that the `> \n` sequence apparently breaks the rendering and adding a newline, in turn, breaks the paragraph structure, the only viable solution was to insert an non-breakable space into the character stream.
<details><summary><h4>Related PRs</h4></summary>
- #261,
- #259 
- #234,
- #122
- #62
</details>

fix: add workaround to make it possible to see quotes spanning multiple paragraphs

---

core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultInstanceSelectionRepository.kt

This PR adds `feddit.org` to the list of default instances (`feddit.de` was removed by #83 and never replaced).

chore: add feddit.org to list of default instances

---

core/l10n/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/l10n/Strings.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/data/SettingsModel.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultSettingsRepository.kt
core/persistence/src/commonMain/sqldelight/com/livefast/eattrash/raccoonforlemmy/core/persistence/settings.sq
core/persistence/src/commonMain/sqldelight/migrations/42.sqm
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsMviModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/resources/SharedStrings.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
unit/mentions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/mentions/InboxMentionsViewModel.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListViewModel.kt
unit/replies/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/replies/InboxRepliesViewModel.kt

This PR adds the possibility to disable the default behaviour which marks posts as read even after they are saved or voted.

feat: add option to not mark posts as read on interaction

---

feature/inbox/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/inbox/main/InboxScreen.kt
feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsScreen.kt
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/main/MainScreen.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/acknowledgements/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/acknowledgements/main/AcknowledgementsScreen.kt
unit/chat/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/chat/InboxChatScreen.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/configurecontentview/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurecontentview/ConfigureContentViewScreen.kt
unit/configurenavbar/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurenavbar/ConfigureNavBarScreen.kt
unit/configureswipeactions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configureswipeactions/ConfigureSwipeActionsScreen.kt
unit/createcomment/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
unit/createpost/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
unit/drafts/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/drafts/DraftsScreen.kt
unit/editcommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/editcommunity/EditCommunityScreen.kt
unit/explore/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/explore/ExploreScreen.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/instanceinfo/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/instanceinfo/InstanceInfoScreen.kt
unit/licences/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/licences/LicencesScreen.kt
unit/manageban/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/manageban/ManageBanScreen.kt
unit/medialist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/medialist/MediaListScreen.kt
unit/modlog/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/modlog/ModlogScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/reportlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

This PR removes custom WindowInsets from Scaffold contents because it is no longer needed with edge to edge enabled and it, actually, could lead to more harm than good.

fix: remove custom WindowInsets from Scaffolds

---

androidApp/build.gradle.kts
androidApp/src/main/java/com/livefast/eattrash/raccoonforlemmy/android/MainActivity.kt
core/appearance/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
core/appearance/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/SolidBarColorWorkaround.kt
core/appearance/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/BarColorProvider.kt
core/appearance/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsMviModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt

This PR makes it possible, if one really wants to, set the "Solid" status bar theme even on Android >= 15.
This is tricky, because the `setOnApplyWindowInsetsListener` should be done in the right moment in the Activity lifecycle otherwise it is never called.
Moreover, it introduces a slight startup overhead because settings have to be read in order to determine the current UI theme and bar theme.

enhancement: add workaround for solid status bar color

---

core/notifications/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageMviModel.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageScreen.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/ZoomableImageViewModel.kt
unit/zoomableimage/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/zoomableimage/di/ZoomableImageModule.kt

This PR improves the mechanism to download and save/share image files used in the app. It involves:
- removing notification dispatching for this kind of events, which is not needed any more because they can be converted to simple MVI intents;
- preventing duplicated even processing by reading the `loading` status before processing them;
- factor out shared code and other minor refactoring interventions.

fix: improve image download and share

---

core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/dto/CommentSortType.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/utils/Mappings.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/main/SettingsScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailMviModel.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt

This PR solves several issues related to comment sort type selection:
- in the settings screen, the last option should not expand because the only available option for comments is `"Top"`
- `"Controversial"` sort type was not mapped, resulting in it being treated as "New" instead
- the post detail screen showed the default (`"New"`) type before loading it from settings, which is poor user experience.
The results which are coming from the server, especially if there are few comments, do not change but this is not an application bug.

fix: comment sort type

---

core/markdown/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt

This PR fixes a couple of issues in spoiler rendering:
- the text before the spoiler was sometimes included in the spoiler body;
- the spoiler body contained sometimes some trailing colon delimiters.

fix: spoiler rendering

---

androidApp/src/main/java/com/livefast/eattrash/raccoonforlemmy/android/MainApplication.kt
core/api/build.gradle.kts
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeImageLoadModule.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeImageLoadModule.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeImageLoadModule.kt
gradle.properties
gradle/libs.versions.toml
iosApp/iosApp/Info.plist
shared/build.gradle.kts
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/App.kt

This PR prepares the ground for #408, making it possible to compile and launch the app (again) in iOS.
It was quite a long time I did not try to build it on iOS targets any more, and there were quite a few changes in the meantime:
- DI was migrated from Koin to Kodein
- image loading with Coil3 (instead of Kamel)
- KSP 2.0
- ...
so some adjustments were needed.
The app now builds and launches on an iOS simulator.

chore: improve iOS support

---

domain/lemmy/usecase/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSiteSupportsHiddenPostsUseCaseTest.kt
domain/lemmy/usecase/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSiteSupportsMediaListUseCaseTest.kt
domain/lemmy/usecase/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSortTypesUseCaseTest.kt
domain/lemmy/usecase/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultIsSiteVersionAtLeastUseCaseTest.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSiteSupportsHiddenPostsUseCase.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSiteSupportsMediaListUseCase.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultGetSortTypesUseCase.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/DefaultIsSiteVersionAtLeastUseCase.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/IsSiteVersionAtLeastUseCase.kt
domain/lemmy/usecase/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/usecase/di/LemmyUseCaseModule.kt

overload invoke operator
This PR refactors `IsVersionAtLeastUseCase` to make it callable (like other use cases in the same package) with the invoke operator.
This is a follow-up on #409 to make it simpler to determine the backend version.

refactor IsSiteVersionAtLeastUseCase

---

core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/provider/DefaultServiceProvider.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/service/v4/AccountServiceV4.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/service/v4/V4.kt
domain/lemmy/repository/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultSiteRepositoryTest.kt
domain/lemmy/repository/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/utils/DefaultSiteVersionDataSourceTest.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/DefaultSiteRepository.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/utils/DefaultSiteVersionDataSource.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/utils/SiteVersionDataSource.kt

This PR  makes it possible to retrieve the current user :
- on Lemmy < 1.0.0 using the GET `v3/site` endpoint (by the `my_user` property in the response)
- on Lemmy >= 1.0.0 using the GET `v4/account` endpoint.
This is the real beginning of the service migration for the new backend version 🎉 (see #349).

feat(api): new get remote account V4

---

core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/service/v3/AuthServiceV3.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/service/v4/AccountServiceV4.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/repository/DefaultAuthRepositoryTest.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLogoutUseCaseTest.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/di/IdentityModule.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/repository/AuthRepository.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/repository/DefaultAuthRepository.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultLogoutUseCase.kt
domain/lemmy/repository/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/lemmy/repository/utils/SiteVersionDataSource.kt

This PR adds the possibility to use the new POST `v4/account/auth/login` and POST `v4/account/auth/logout` endpoints (replacing the old POST `v3/user/login` and POST `v3/user/logout`).
This is another required step in the migration towards Lemmy 1.0.0 (see #349).

feat(api): add support for V4 login and logout methods

---

core/appearance/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/main/MainScreen.kt

This PR fixes the colors of the status bar (depending on the theme), plus it also fixes the insets on newer versions of Android.

fix: status bar inset and color

---

build-logic/convention/src/main/kotlin/plugins/SpotlessPlugin.kt
gradle/libs.versions.toml

This PR removes the hardcoded `io.nlopez.compose.rules:ktlint:0.4.22` string from `SpotlessPlugin` and reads it from the version catalog.

chore: read ktlint-compose-rules from version catalog

---

core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/provider/DefaultServiceProvider.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/provider/ServiceProvider.kt
core/persistence/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultAccountRepositoryTest.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/dao/AccountDao.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/dao/DefaultAccountDao.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/dao/Extensions.kt
core/persistence/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/persistence/repository/DefaultAccountRepository.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/repository/DefaultApiConfigurationRepositoryTest.kt
domain/identity/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultSwitchAccountUseCaseTest.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/di/IdentityModule.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/repository/DefaultApiConfigurationRepository.kt
domain/identity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/domain/identity/usecase/DefaultSwitchAccountUseCase.kt
unit/managesubscriptions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/managesubscriptions/di/ManageSubscriptionsModule.kt

This PR makes it possible to easily observe data changes from the local DB. This is going to be used in the future to improve app startup and account change scenarios.
Moreover, since we're at it, this also removes some other workaround to register observers for changes (e.g. the current instance).

refactor: improve observability

---

core/navigation/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/navigation/DefaultNavigationAdapter.kt
core/navigation/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/navigation/NavigationAdapter.kt

This PR solves a bug due to which, after #464, tapping twice on the back button can pop all entries from the backstack. The solution is adding a throttling behaviour to the nav controller management.

fix: add throttling behaviour to navigation

---

core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/di/ApiModule.kt
core/api/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/api/provider/DefaultServiceProvider.kt
core/preferences/src/androidUnitTest/kotlin/com/livefast/eattrash/raccoonforlemmy/core/preferences/appconfig/RemoteAppConfigDataSourceTest.kt
core/preferences/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/preferences/appconfig/AppConfig.kt
core/preferences/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/preferences/appconfig/RemoteAppConfigDataSource.kt
core/preferences/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/preferences/di/AppConfigModule.kt
gradle/libs.versions.toml

This PR adds the `version` field to the AppConfig object, which will be needed for future implementations/migration.

refactor: add version to remote app config

---

core/architecture/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/architecture/di/GetViewModel.kt
core/architecture/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/architecture/di/ViewModelBindUtils.kt

This PR makes sure there are no overlapping DI tags for `ViewModel` bindings, which could happen with code obfuscation in release builds if the class `simpleName` were used. Switching to `qualifiedName` solves the issue.

fix(di): make sure unique tags are used for ViewModel bindings

---

core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/CommentCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/InboxCard.kt
core/commonui/lemmyui/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/clipboard/DefaultClipboardHelper.kt
core/utils/src/androidMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeClipboardModule.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/clipboard/ClipboardHelper.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeClipboardModule.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/Utils.kt
core/utils/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/UtilsModule.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/clipboard/DefaultClipboardHelper.kt
core/utils/src/iosMain/kotlin/com/livefast/eattrash/raccoonforlemmy/core/utils/di/NativeClipboardModule.kt
unit/communitydetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
unit/multicommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
unit/postdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
unit/postlist/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/postlist/PostListScreen.kt
unit/rawcontent/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/rawcontent/RawContentDialog.kt
unit/userdetail/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt

Compose 1.8.0 deprecated `ClipboardManager` in favor of `Clipboard`, which exposes a suspending API (changelog [here](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.8.0)).
With a delay of some month, I finally took the time to complete the migration. This involves using a helper (multiplatform) class, because native APIs are not equal (and in iOS it is still experimental).

chore: migrate from ClipboardManager to Clipboard

---

feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
feature/profile/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/profile/notlogged/ProfileNotLoggedScreen.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsViewModel.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/di/AccountSettingsModule.kt

This PR add a "Switch account" button in the profile screen when there is an authentication issue. This makes it possible to change account when, e.g., your instance is down.

enhancement: add switch account button on auth failure

---

feature/inbox/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/inbox/main/InboxScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontScreen.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/colors/SettingsColorAndFontViewModel.kt
feature/settings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/feature/settings/di/SettingsTabModule.kt
unit/accountsettings/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
unit/configurenavbar/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configurenavbar/ConfigureNavBarScreen.kt
unit/configureswipeactions/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/configureswipeactions/ConfigureSwipeActionsScreen.kt
unit/editcommunity/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/editcommunity/EditCommunityScreen.kt
unit/filteredcontents/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
unit/instanceinfo/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/unit/instanceinfo/InstanceInfoScreen.kt

This PR moves all the "submit" buttons in the `bottomBar` slot of Material 3 `Scaffold`s in order to have automatic management of navigation insets.
Affected screens:
- web preferences (remote account settings)
- community edit
- configure bottom navigation bar

fix: settings submit bottom insets
